name: Nix CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - prod
    tags:
      - '**'

env: 
  CI_NIXOS_HOSTNAMES: ryan-worldcoin-hil # space delineated

jobs:
  liveusb:
    name: Build NixOS Installer
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # pin@v27

      - name: Build diskoImagesScript
        run: |
          set -Eeuxo pipefail
          nix build .#nixosConfigurations.liveusb.config.system.build.diskoImagesScript
          ls -alhR ./result
      - name: Run diskoImagesScript
        run: |
          set -Eeuxo pipefail
          ./result
          ls -lh *.raw
      - name: Compress artifact
        run: |
          set -Eeuxo pipefail
          mkdir -p artifacts
          zstd --compress liveusb.raw -o artifacts/liveusb.raw.zst
          ls -aRsh artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        if: github.event_name == 'workflow_dispatch' || format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
        with:
          # upload v4 doesn't support writing multiple times to the same artifact name.
          # so its important that we name it after the workflow and not something
          # general like "artifacts"
          name: nix
          path: artifacts/*
          compression-level: 0
          if-no-files-found: error
          retention-days: 14
